build_steps: &build_steps
  working_directory: ~/repo
  steps:
    - checkout
    - run: bundle install
    - run: bundle exec rake

version: 2
jobs:
  test_ruby-2.3:
    <<: *build_steps
    docker:
      - image: circleci/ruby:2.3
  test_ruby-2.4:
    <<: *build_steps
    docker:
      - image: circleci/ruby:2.4
  test_ruby-2.5:
    <<: *build_steps
    docker:
      - image: circleci/ruby:2.5
  release:
    docker:
      - image: circleci/ruby:2.5
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rake release

workflows:
  version: 2
  test_and_release:
    jobs:
      - test_ruby-2.3:
          filters:
            tags:
              only: /.*/
      - test_ruby-2.4:
          filters:
            tags:
              only: /.*/
      - test_ruby-2.5:
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - test_ruby-2.3
            - test_ruby-2.4
            - test_ruby-2.5
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
